pilot:
  navigation:
    lookahead_meters: 2
    lookahead_max: 5
    lookahead_speed_factor: 0.08
    l: 1.8
    k: 7
  speed_control:
    default_accel: 1.0
    cornering_accel: 0.4
    steering_threshold: 0.5

    curvature_gain: 1.0
    hairpin_curvature: 5

    hairpin_threshold: 0.8
    haripin_curvature: 10
    hairpin_accel: 0.1
    hairpin_brake_speed: 10
  rescue:
    stuck_frames_limit: 50
    active_after_meters: 10
    stuck_diff_dist_epsilon: 0.5
    rescue_duration: 11
banana:
  detection:
    max_distance: 9
    safety_width: 1.3
  avoidance:
    steering_force: 0.9
    acceleration: 0.3
  edge_safety:
    max_center_dist: 5
    max_border_dist_percentage: 0.85
    steering_correction: 0.5
    correction_accel: 0.1
nitro:
  detection:
    steering_threshold_nitro: 0.4404211270076367
    min_acceleration: 0.6166195263114425
drift:
  drift_steer_angle: 0.7
  far_lookahead: 7
  near_lookahead: 2
  far_target_threshold: 2
  steer_trigger: 0.6
  confirmation_frames: 15
  min_speed: 15
  max_dist_center: 10
  exit_target_threshold: 0.5
  cooldown_frames: 15
  drift_accel: 0.9
avoid_karts:
  safe_distance: 2
  avoid_steer: 0.3
  side_threshold: 1
