pilot:
  brain:
    kp: 9
    kd: 6
  navigation:
    lookahead_meters: 10.99771223077839
    lookahead_max: 14.65533391278857
    min_dist_safety: 1.9050938421276995
    apex_offset: 0.6
    lookahead_speed_factor: 0.2
    k: 16.46946813046176
  speed_control:
    default_accel: 1.0
    cornering_accel: 0.412314499739835
    steering_threshold: 0.8663366608853442
    hairpin_threshold: 0.7536038497516317
    hairpin_accel:  0.3913199835747871
    hairpin_brake_speed: 14.336313111828359
  rescue:
    stuck_frames_limit: 40
    active_after_meters: 10
    stuck_diff_dist_epsilon: 1
    rescue_duration: 20
banana:
  detection:
    max_distance: 11.194859851398817
    safety_width: 1.631524005856674
  avoidance:
    steering_force: 0.911856987655246
    acceleration: 0.49941865954191633
  edge_safety:
    max_center_dist: 6
    steering_correction: 0.35848429039351465
    correction_accel: 0.49876099956960307
nitro:
  detection:
    steering_threshold_nitro: 0.4404211270076367
    min_acceleration: 0.6166195263114425
drift:
  drift_steer_angle: 0.6
  far_lookahead: 15
  near_lookahead: 2.716552385567403
  far_target_threshold: 2
  steer_trigger: 0.7
  confirmation_frames: 10
  min_speed: 10
  max_dist_center: 5
  exit_target_threshold: 0.5
  cooldown_frames: 15
  drift_accel: 1.0
avoid_karts:
  safe_distance: 8
  avoid_steer: 0.3
  side_threshold: 2
